[[ -r ~/.bashrc ]] && . ~/.bashrc

PATH=$PATH:/System/Library/Frameworks/Python.framework/Versions/2.7/bin
PATH=$PATH:$(brew --prefix coreutils)/libexec/gnubin

# Source brew bash completion.
source $(brew --prefix)/etc/bash_completion

# To stop clang errors thanks to Xcode updates.
# https://langui.sh/2014/03/10/wunused-command-line-argument-hard-error-in-future-is-a-harsh-mistress/
export ARCHFLAGS="-Wno-error=unused-command-line-argument-hard-error-in-future"
